import { Link } from 'react-router-dom';
import { resolvePlayOrigin, CANONICAL_PLAY_URL } from '@rushpoint/shared';
import { useT, useLanguage } from './LanguageContext';

// Where the participant app lives, resolved exactly as the Builder, Dashboard and
// Run Console resolve it. It used to be a literal here, which is how this link
// kept pointing at the apex after the participant app moved off it
// (change: marketing-to-apex): the apex now serves the marketing site, so the
// literal silently became a link to a different product.
const PLAY_URL = import.meta.env.DEV
  ? resolvePlayOrigin(window.location.origin)
  : ((import.meta.env.VITE_PLAY_URL as string | undefined) ?? CANONICAL_PLAY_URL);

/**
 * Persistent app-chrome footer carrying the legal documents.
 *
 * The /privacy and /terms routes already existed but had no entry point once a
 * creator was signed in: the logged-out landing page (AuthGate) linked to them,
 * so the only way back was to sign out or type the URL. App-store and GDPR
 * reviews expect the policy to be reachable from inside the product, not just
 * from the marketing page.
 *
 * Uses <Link>, not <a>: these are real routes in this SPA, so an anchor would
 * force a full document reload and drop the session state.
 */
export default function AppFooter() {
  const t = useT();
  const { lang } = useLanguage();
  const linkClass = 'hover:text-[--ink-1] hover:underline transition-colors rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rp-fire/60';
  return (
    <footer className="relative z-10 border-t border-[--rp-border] mt-8">
      <div className="max-w-6xl mx-auto px-4 py-5 flex flex-wrap items-center justify-center gap-x-3 gap-y-1 text-xs text-[--ink-3]">
        <Link to="/privacy" className={linkClass}>{t.common.privacyLink}</Link>
        <span aria-hidden="true">·</span>
        <Link to="/terms" className={linkClass}>{t.common.termsLink}</Link>
        <span aria-hidden="true">·</span>
        {/*
          The marketing pages are STATIC FILES on the participant origin, generated by
          scripts/build-landing-pages.ts, so this is a real <a> to another origin and not
          a <Link>: react-router has no route for it and would render a dead in-app path.
          It also matters for SEO, which is why the link exists at all: these pages need
          an inbound link from a surface that is not themselves, or they sit orphaned and
          are discovered only through the sitemap. The href follows the reader's current
          language, so the console never sends a Hebrew speaking creator to English copy.
        */}
        <a
          href={`${PLAY_URL}/${lang}/`}
          className={linkClass}
          target="_blank"
          rel="noreferrer"
        >
          {t.common.ideasLink}
        </a>
      </div>
    </footer>
  );
}
