// Ephemeral end-to-end verification of the v2 multi-tenant model against the
// running emulator. Exercises the full creator → run → participant → finalize
// path through the public callable API (createGame → updateGame → launchRun →
// getJoinInfo → joinRun → startTeams → getMyTeamState → verifyStationCode /
// completeTask → finalizeRun). Each "party" gets its own anonymous identity,
// mirroring the two-app reality (creator-web + play-web).
//
//   node scripts/e2e-verify-v2.mjs
//
import { initializeApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, signInAnonymously, signInWithCustomToken } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, doc, setDoc } from 'firebase/firestore';

const PROJECT = 'rushpoint-pwa-7daaa';

function makeParty(name) {
  const app = initializeApp(
    { apiKey: 'emulator-key', projectId: PROJECT, appId: `emu-${name}` },
    name,
  );
  const auth = getAuth(app);
  const functions = getFunctions(app);
  const db = getFirestore(app);
  connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
  connectFunctionsEmulator(functions, '127.0.0.1', 5001);
  connectFirestoreEmulator(db, '127.0.0.1', 8080);
  return {
    auth,
    call: (fn, data) => httpsCallable(functions, fn)(data).then((r) => r.data),
    setDocAt: (path, data) => setDoc(doc(db, path), data),
  };
}

let failures = 0;
function check(label, cond, detail) {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? ' :: ' + detail : ''}`);
  if (!cond) failures++;
}

async function main() {
  const creator = makeParty('creator');
  const player = makeParty('player');
  const staff = makeParty('staff');

  const creatorCred = await signInAnonymously(creator.auth);
  const playerCred = await signInAnonymously(player.auth);
  await signInAnonymously(staff.auth); // upgraded to a staff custom token below
  console.log('Creator uid:', creatorCred.user.uid);
  console.log('Player  uid:', playerCred.user.uid, '\n');

  // ── 1. Creator builds a game ────────────────────────────────────────────────
  const { gameId } = await creator.call('createGame', {
    title: 'E2E Verify Game',
    description: 'Generated by e2e-verify-v2',
    mode: 'team',
  });
  check('createGame returns a gameId', !!gameId, gameId);

  // ── 1b. Free mode (payments off) ────────────────────────────────────────────
  // PAYMENTS_ENABLED is false at launch: every run is free (no credits, no Pro)
  // and buying is disabled. A brand-new 0-credit free-plan creator must launch
  // unlimited runs with no wallet decrement — this e2e launches 4 runs on a
  // wallet that never buys a credit.
  const wallet0 = await creator.call('getWalletStatus');
  check('free mode: getWalletStatus reports paymentsEnabled:false', wallet0?.paymentsEnabled === false, JSON.stringify(wallet0));
  check('free mode: new creator has 0 credits', wallet0?.eventCredits === 0, JSON.stringify(wallet0));

  let purchaseRejected = false;
  try {
    await creator.call('purchaseCredits', { packageId: 'pro_pack' });
  } catch (e) {
    purchaseRejected = /disabled/i.test(e.message);
  }
  check('free mode: purchaseCredits is rejected (payments disabled)', purchaseRejected);

  let subscribeRejected = false;
  try {
    await creator.call('subscribePro', { interval: 'month' });
  } catch (e) {
    subscribeRejected = /disabled/i.test(e.message);
  }
  check('free mode: subscribePro is rejected (payments disabled)', subscribeRejected);

  const CODE_TASK_ID = 'task-code-1';
  const PHOTO_TASK_ID = 'task-photo-1';
  const PLAIN_TASK_ID = 'task-plain-1';
  const stages = [
    {
      id: 'stage-1',
      order: 0,
      title: 'Stage One — code station',
      tasks: [
        {
          id: CODE_TASK_ID,
          title: 'Find the codeword',
          type: 'station',
          coordinates: { lat: 31.79, lng: 35.16 },
          difficulty: 3,
          estimatedMinutes: 10,
          pointValue: 100,
          maxConcurrentTeams: 3,
          smart: {
            enabled: true,
            verificationType: 'code_verification',
            hasCode: true,
            secretCode: 'ZION',
            codeInputLabel: 'Enter codeword',
          },
        },
      ],
    },
    {
      id: 'stage-2',
      order: 1,
      title: 'Stage Two — photo station (staff review)',
      tasks: [
        {
          id: PHOTO_TASK_ID,
          title: 'Selfie at the gate',
          type: 'photo',
          coordinates: { lat: 31.795, lng: 35.165 },
          difficulty: 2,
          estimatedMinutes: 6,
          pointValue: 70,
          maxConcurrentTeams: 3,
          smart: {
            enabled: true,
            verificationType: 'photo_upload',
            autoApprove: false, // requires a staff approval
          },
        },
      ],
    },
    {
      id: 'stage-3',
      order: 2,
      title: 'Stage Three — plain task',
      isFinal: true,
      tasks: [
        {
          id: PLAIN_TASK_ID,
          title: 'Reach the summit',
          type: 'navigation',
          coordinates: { lat: 31.8, lng: 35.17 },
          difficulty: 2,
          estimatedMinutes: 8,
          pointValue: 80,
          maxConcurrentTeams: 3,
        },
      ],
    },
  ];

  await creator.call('updateGame', {
    gameId,
    stages,
    scoringPreset: 'smart_weighted',
  });
  check('updateGame accepted 3 stages', true);

  // ── 2. Launch a run ─────────────────────────────────────────────────────────
  const { runId, accessCode } = await creator.call('launchRun', { gameId });
  check('launchRun returns runId + accessCode', !!runId && !!accessCode, accessCode);
  const walletAfterLaunch = await creator.call('getWalletStatus');
  check('free mode: launch did not decrement the wallet (still 0 credits)',
    walletAfterLaunch?.eventCredits === 0, JSON.stringify(walletAfterLaunch));

  // ── 3. Participant pre-join lookup ──────────────────────────────────────────
  const joinInfo = await player.call('getJoinInfo', { code: accessCode });
  check('getJoinInfo resolves the game title', joinInfo?.title === 'E2E Verify Game', joinInfo?.title);
  check('getJoinInfo exposes registrationFields', Array.isArray(joinInfo?.registrationFields));
  check('getJoinInfo does NOT leak game stages', joinInfo?.stages === undefined);
  check('getJoinInfo returns a derived GPS requirement', joinInfo?.requirement === 'gps' || joinInfo?.requirement === 'anywhere', joinInfo?.requirement);

  // ── 4. Join the run ─────────────────────────────────────────────────────────
  const joinRes = await player.call('joinRun', {
    code: accessCode,
    displayName: 'The Test Lions',
    memberNames: ['Ari', 'Dan'],
  });
  check('joinRun succeeds', joinRes?.teamId === playerCred.user.uid, joinRes?.teamId);
  check('joinRun is first-time (not alreadyJoined)', joinRes?.alreadyJoined === false);

  // idempotency
  const joinAgain = await player.call('joinRun', { code: accessCode, displayName: 'The Test Lions' });
  check('joinRun is idempotent', joinAgain?.alreadyJoined === true);

  // ── 5. Creator starts the teams ─────────────────────────────────────────────
  const startRes = await creator.call('startTeams', { gameId, runId });
  check('startTeams launched 1 team', startRes?.launched === 1, JSON.stringify(startRes));

  // ── 6. Participant reads their live state ───────────────────────────────────
  let state = await player.call('getMyTeamState', { code: accessCode });
  check('getMyTeamState returns the team', state?.team?.displayName === 'The Test Lions');
  check('team is active after startTeams', state?.team?.status === 'active', state?.team?.status);
  check('first stage is active', state?.team?.stages?.[0]?.status === 'active');
  const activeTask = state?.activeStageTasks?.[0];
  check('active task content is exposed', activeTask?.id === CODE_TASK_ID);
  check('secretCode is stripped from participant payload', activeTask?.smart?.secretCode === undefined);

  // ── 7. Wrong code is rejected, correct code advances ────────────────────────
  let wrongRejected = false;
  try {
    await player.call('verifyStationCode', {
      ownerUid: creatorCred.user.uid, gameId, runId,
      teamId: playerCred.user.uid, taskId: CODE_TASK_ID, code: 'NOPE',
    });
  } catch (e) {
    wrongRejected = /incorrect code/i.test(e.message);
  }
  check('verifyStationCode rejects a wrong code', wrongRejected);

  // [anti-cheat row 38] a participant may NOT act on another team — a payload
  // teamId that isn't the caller is rejected with permission-denied (IDOR fix).
  let idorRejected = false;
  try {
    await player.call('verifyStationCode', {
      ownerUid: creatorCred.user.uid, gameId, runId,
      teamId: 'some-other-team-uid', taskId: CODE_TASK_ID, code: 'zion',
    });
  } catch (e) {
    idorRejected = e.code === 'functions/permission-denied' || /another team/i.test(e.message);
  }
  check('verifyStationCode rejects acting on another team (IDOR)', idorRejected);

  let idorPhotoRejected = false;
  try {
    await player.call('submitStationPhoto', {
      ownerUid: creatorCred.user.uid, gameId, runId,
      teamId: 'some-other-team-uid', taskId: CODE_TASK_ID,
      photoUrl: 'https://firebasestorage.googleapis.com/v0/b/rushpoint-pwa-7daaa.appspot.com/o/x.jpg?alt=media',
    });
  } catch (e) {
    idorPhotoRejected = e.code === 'functions/permission-denied' || /another team/i.test(e.message);
  }
  check('submitStationPhoto rejects acting on another team (IDOR)', idorPhotoRejected);

  const verifyRes = await player.call('verifyStationCode', {
    ownerUid: creatorCred.user.uid, gameId, runId,
    teamId: playerCred.user.uid, taskId: CODE_TASK_ID, code: 'zion', // case-insensitive
  });
  check('verifyStationCode accepts the correct code', verifyRes?.verified === true);

  // ── 8. Stage 1 done → stage 2 should unlock ─────────────────────────────────
  state = await player.call('getMyTeamState', { code: accessCode });
  check('stage 1 completed', state?.team?.stages?.[0]?.status === 'completed', state?.team?.stages?.[0]?.status);
  check('stage 2 unlocked (active)', state?.team?.stages?.[1]?.status === 'active', state?.team?.stages?.[1]?.status);
  check('code task scored > 0', (state?.team?.stages?.[0]?.tasks?.[0]?.earnedScore ?? 0) > 0,
    String(state?.team?.stages?.[0]?.tasks?.[0]?.earnedScore));

  // ── 8b. Live leaderboard mid-run (refreshLeaderboard) ───────────────────────
  const lbCtx = { ownerUid: creatorCred.user.uid, gameId, runId };
  const lbHidden = await creator.call('refreshLeaderboard', { ...lbCtx, publish: false });
  check('refreshLeaderboard returns live rankings mid-run', (lbHidden?.rankings?.length ?? 0) === 1,
    JSON.stringify(lbHidden?.rankings?.[0]));
  check('refreshLeaderboard stays unpublished by default', lbHidden?.published === false);
  let midState = await player.call('getMyTeamState', { code: accessCode });
  check('run is still live after refresh (not finished)', midState?.run?.status !== 'finished', midState?.run?.status);
  check('unpublished standings are hidden from participant', midState?.run?.leaderboard?.published === false);

  // Public, shareable leaderboard is gated on publish: hidden before, shown after.
  const boardBefore = await player.call('getPublicLeaderboard', { code: accessCode });
  check('public leaderboard hides rankings until published',
    boardBefore?.published === false && (boardBefore?.rankings?.length ?? 0) === 0);

  const lbShown = await creator.call('refreshLeaderboard', { ...lbCtx, publish: true });
  check('refreshLeaderboard can publish to teams', lbShown?.published === true);
  midState = await player.call('getMyTeamState', { code: accessCode });
  check('published standings are visible to participant', midState?.run?.leaderboard?.published === true);

  const boardAfter = await player.call('getPublicLeaderboard', { code: accessCode });
  check('public leaderboard exposes rankings once published',
    boardAfter?.published === true && (boardAfter?.rankings?.length ?? 0) === 1,
    JSON.stringify(boardAfter?.rankings?.[0]));

  // ── 8c. Photo task: submit → staff review → advance ─────────────────────────
  // M3: submitStationPhoto only accepts Firebase Storage URLs from our bucket.
  // row 41: the photo must live under the caller's OWN run/team folder.
  const STORAGE_PHOTO_URL =
    `https://firebasestorage.googleapis.com/v0/b/rushpoint-pwa-7daaa.appspot.com/o/${encodeURIComponent(`runs/${runId}/teams/${playerCred.user.uid}/selfie.jpg`)}?alt=media`;

  // [M3] an external photo URL must be rejected with invalid-argument.
  let externalPhotoRejected = false;
  try {
    await player.call('submitStationPhoto', {
      ownerUid: creatorCred.user.uid, gameId, runId,
      teamId: playerCred.user.uid, taskId: PHOTO_TASK_ID,
      photoUrl: 'https://example.com/evil.jpg',
    });
  } catch (e) {
    externalPhotoRejected = e.code === 'functions/invalid-argument' || /Firebase Storage URL/i.test(e.message);
  }
  check('submitStationPhoto rejects an external (non-Storage) photo URL', externalPhotoRejected);

  const photoSubmit = await player.call('submitStationPhoto', {
    ownerUid: creatorCred.user.uid, gameId, runId,
    teamId: playerCred.user.uid, taskId: PHOTO_TASK_ID,
    photoUrl: STORAGE_PHOTO_URL,
  });
  check('submitStationPhoto accepts a photo (pending, not auto-approved)',
    photoSubmit?.submitted === true && photoSubmit?.autoApproved === false, JSON.stringify(photoSubmit));

  state = await player.call('getMyTeamState', { code: accessCode });
  check('submission is stored NESTED under taskSubmissions (not a literal dotted key)',
    state?.team?.taskSubmissions?.[PHOTO_TASK_ID]?.status === 'pending',
    JSON.stringify(state?.team?.taskSubmissions ?? {}));
  check('photo stage stays active until reviewed', state?.team?.stages?.[1]?.status === 'active',
    state?.team?.stages?.[1]?.status);

  // Staff joins via PIN and approves the photo
  const { pin } = await creator.call('inviteStaff', {
    ownerUid: creatorCred.user.uid, gameId, runId, name: 'E2E Marshal', permissions: ['review_photos'],
  });
  check('inviteStaff returns a PIN', !!pin, pin);

  // [anti-cheat row 40] a different caller that fails the PIN 5× is locked out of
  // this run — even a subsequent attempt with the CORRECT pin is refused. The
  // lockout short-circuits before the invite lookup, so it never burns the PIN.
  const locker = makeParty('locker');
  await signInAnonymously(locker.auth);
  for (let i = 0; i < 5; i++) {
    try { await locker.call('staffSignIn', { ownerUid: creatorCred.user.uid, gameId, runId, pin: '000000' }); } catch { /* expected */ }
  }
  let lockoutHit = false;
  try {
    await locker.call('staffSignIn', { ownerUid: creatorCred.user.uid, gameId, runId, pin });
  } catch (e) { lockoutHit = e.code === 'functions/resource-exhausted' || /too many/i.test(e.message); }
  check('staffSignIn locks out after 5 failed attempts (even with correct PIN)', lockoutHit);

  const staffTok = await staff.call('staffSignIn', {
    ownerUid: creatorCred.user.uid, gameId, runId, pin,
  });
  check('staffSignIn mints a custom token', !!staffTok?.customToken && staffTok?.name === 'E2E Marshal');
  await signInWithCustomToken(staff.auth, staffTok.customToken);

  const review = await staff.call('reviewStationSubmission', {
    ownerUid: creatorCred.user.uid, gameId, runId,
    teamId: playerCred.user.uid, taskId: PHOTO_TASK_ID, approved: true,
  });
  check('reviewStationSubmission approves', review?.ok === true && review?.approved === true);

  state = await player.call('getMyTeamState', { code: accessCode });
  check('review marks the submission approved (nested update)',
    state?.team?.taskSubmissions?.[PHOTO_TASK_ID]?.status === 'approved',
    state?.team?.taskSubmissions?.[PHOTO_TASK_ID]?.status);
  check('approved photo completes the stage', state?.team?.stages?.[1]?.status === 'completed',
    state?.team?.stages?.[1]?.status);
  check('final stage unlocked after photo', state?.team?.stages?.[2]?.status === 'active',
    state?.team?.stages?.[2]?.status);

  // ── 9. Complete the final plain task ────────────────────────────────────────
  const completeRes = await player.call('completeTask', {
    taskId: PLAIN_TASK_ID, code: accessCode, lat: 31.8, lng: 35.17,
  });
  check('completeTask on final task succeeds', completeRes?.ok === true);

  state = await player.call('getMyTeamState', { code: accessCode });
  check('all stages completed', state?.team?.stages?.every((s) => s.status === 'completed'),
    state?.team?.stages?.map((s) => s.status).join(','));
  check('team marked finished', !!state?.team?.finishedAt || state?.team?.status === 'finished',
    state?.team?.status);

  // ── 10. Finalize the run ────────────────────────────────────────────────────
  const fin = await creator.call('finalizeRun', { gameId, runId });
  check('finalizeRun returns rankings', Array.isArray(fin?.rankings) && fin.rankings.length === 1);
  check('our team is ranked #1', fin?.rankings?.[0]?.teamId === playerCred.user.uid, JSON.stringify(fin?.rankings?.[0]));
  check('final score is positive', (fin?.rankings?.[0]?.score ?? 0) > 0, String(fin?.rankings?.[0]?.score));

  // ── 10b. Data-retention prune of a finished run ─────────────────────────────
  // pruneRunNow strips raw PII (GPS pings + photo URLs) while keeping scores.
  // This run had a submitted photo, so at least one photoUrl should be cleared.
  const prune = await creator.call('pruneRunNow', {
    ownerUid: creatorCred.user.uid, gameId, runId,
  });
  check('pruneRunNow succeeds + clears the submitted photo URL',
    prune?.ok === true && prune?.photoUrlsCleared >= 1, JSON.stringify(prune));
  const prune2 = await creator.call('pruneRunNow', {
    ownerUid: creatorCred.user.uid, gameId, runId,
  });
  check('pruneRunNow is idempotent (nothing left to clear)',
    prune2?.ok === true && prune2?.photoUrlsCleared === 0, JSON.stringify(prune2));

  // ── 11. A late participant cannot join a finished run ───────────────────────
  let lateRejected = false;
  try {
    await staff.call('joinRun', { code: accessCode, displayName: 'Latecomers' });
  } catch (e) {
    lateRejected = /already finished/i.test(e.message);
  }
  check('joinRun rejects a finished run', lateRejected);

  // ── 12. Partial-completion stage + locationless task ────────────────────────
  // A stage with 2 tasks but requiredTaskCount=1: completing ONE finishes the
  // stage and auto-skips the other. One task is locationless (no coordinates).
  const player2 = makeParty('player2');
  const p2 = await signInAnonymously(player2.auth);

  const { gameId: g2 } = await creator.call('createGame', { title: 'Pick-One Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g2,
    scoringPreset: 'fixed_points_speed',
    stages: [{
      id: 'st-pick', order: 0, title: 'Pick one', isFinal: true, requiredTaskCount: 1,
      tasks: [
        { id: 'pk-a', title: 'Located task', type: 'field', coordinates: { lat: 31.78, lng: 35.21 }, difficulty: 3, estimatedMinutes: 5, pointValue: 60, maxConcurrentTeams: 3 },
        { id: 'pk-b', title: 'Anywhere task', type: 'self_report', locationless: true, coordinates: { lat: 0, lng: 0 }, difficulty: 3, estimatedMinutes: 5, pointValue: 60, maxConcurrentTeams: 3 },
      ],
    }],
  });
  const { runId: r2, accessCode: c2 } = await creator.call('launchRun', { gameId: g2 });
  await player2.call('joinRun', { code: c2, displayName: 'Solo' });
  await creator.call('startTeams', { gameId: g2, runId: r2 });

  // Routing assigns one of the two; complete whichever it picked.
  let s2 = await player2.call('getMyTeamState', { code: c2 });
  const assigned = s2?.team?.stages?.[0]?.tasks?.find((t) => t.status === 'assigned');
  check('partial stage routes exactly one task', !!assigned, assigned?.taskId);
  await player2.call('completeTask', { taskId: assigned.taskId, code: c2, lat: 31.78, lng: 35.21 });

  s2 = await player2.call('getMyTeamState', { code: c2 });
  const tasks2 = s2?.team?.stages?.[0]?.tasks ?? [];
  const done = tasks2.filter((t) => t.status === 'completed').length;
  const skipped = tasks2.filter((t) => t.status === 'skipped').length;
  check('completing 1 of 2 finishes the partial stage', s2?.team?.stages?.[0]?.status === 'completed', s2?.team?.stages?.[0]?.status);
  check('the unneeded task is auto-skipped', done === 1 && skipped === 1, `done=${done} skipped=${skipped}`);
  check('team finished after the single required task', s2?.team?.status === 'finished', s2?.team?.status);

  // ── 13. Paid hints (reveal text, charge once, idempotent) ───────────────────
  const { gameId: g3 } = await creator.call('createGame', { title: 'Hint Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g3,
    scoringPreset: 'fixed_points_speed',
    stages: [{
      id: 'st-h', order: 0, title: 'Riddle', isFinal: true,
      tasks: [{
        id: 'h-1', title: 'Solve the riddle', type: 'smart_station',
        coordinates: { lat: 31.78, lng: 35.21 }, difficulty: 4, estimatedMinutes: 5, pointValue: 100, maxConcurrentTeams: 3,
        smart: { enabled: true, verificationType: 'code_verification', hasCode: true, secretCode: 'OLIVE' },
        hint: 'It grows on a tree and makes oil.', hintPenalty: 30,
      }],
    }],
  });
  const { runId: r3, accessCode: c3 } = await creator.call('launchRun', { gameId: g3 });
  const player3 = makeParty('player3');
  await signInAnonymously(player3.auth);
  await player3.call('joinRun', { code: c3, displayName: 'Riddler' });
  await creator.call('startTeams', { gameId: g3, runId: r3 });

  // The hint TEXT must not be leaked in the task payload.
  const s3 = await player3.call('getMyTeamState', { code: c3 });
  const htask = s3?.activeStageTasks?.[0];
  check('hint text is NOT leaked to participants', htask?.hint === undefined && htask?.hasHint === true, JSON.stringify({ hint: htask?.hint, hasHint: htask?.hasHint }));

  const hintRes = await player3.call('requestTaskHint', { ownerUid: creatorCred.user.uid, gameId: g3, runId: r3, taskId: 'h-1' });
  check('requestTaskHint returns the hint + charges the cost', hintRes?.hint === 'It grows on a tree and makes oil.' && hintRes?.penalty === 30, JSON.stringify(hintRes));

  const afterHint = await player3.call('getMyTeamState', { code: c3 });
  check('hint penalty applied to bonusPenalty', afterHint?.team?.bonusPenalty === 30, String(afterHint?.team?.bonusPenalty));

  const hintAgain = await player3.call('requestTaskHint', { ownerUid: creatorCred.user.uid, gameId: g3, runId: r3, taskId: 'h-1' });
  check('second hint request does NOT double-charge', hintAgain?.alreadyUsed === true && hintAgain?.penalty === 0, JSON.stringify(hintAgain));
  const afterAgain = await player3.call('getMyTeamState', { code: c3 });
  check('bonusPenalty unchanged after re-request', afterAgain?.team?.bonusPenalty === 30, String(afterAgain?.team?.bonusPenalty));

  // ── 14. New task types: quiz · numeric · geofence · sequence ────────────────
  const { gameId: g4 } = await creator.call('createGame', { title: 'Task-Types Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g4,
    scoringPreset: 'fixed_points_speed',
    stages: [
      { id: 's-quiz', order: 0, title: 'Quiz', tasks: [{
        id: 'q1', title: 'Capital of France?', type: 'quiz',
        coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 2, estimatedMinutes: 2, pointValue: 50, maxConcurrentTeams: 9,
        choices: ['Paris', 'London', 'Rome'], answers: ['Paris'],
      }] },
      { id: 's-num', order: 1, title: 'Numeric', tasks: [{
        id: 'n1', title: 'How many arches? (±1)', type: 'numeric',
        coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 2, estimatedMinutes: 2, pointValue: 50, maxConcurrentTeams: 9,
        numericAnswer: 12, numericTolerance: 1,
      }] },
      { id: 's-geo', order: 2, title: 'Geofence', tasks: [{
        id: 'gf1', title: 'Reach the gate', type: 'geofence',
        coordinates: { lat: 31.78, lng: 35.21 }, geofenceRadiusMeters: 60, difficulty: 2, estimatedMinutes: 3, pointValue: 50, maxConcurrentTeams: 9,
      }, {
        id: 'ex1', title: 'Exact arrival', type: 'field', triggerMode: 'exact',
        coordinates: { lat: 31.78, lng: 35.21 }, geofenceRadiusMeters: 4, difficulty: 2, estimatedMinutes: 3, pointValue: 50, maxConcurrentTeams: 9,
      }, {
        id: 'in1', title: 'Instant task', type: 'field', triggerMode: 'instant',
        coordinates: { lat: 0, lng: 0 }, difficulty: 2, estimatedMinutes: 1, pointValue: 50, maxConcurrentTeams: 9,
      }] },
      { id: 's-seq', order: 3, title: 'Sequence', isFinal: true, tasks: [{
        id: 'sq1', title: 'Three steps', type: 'sequence',
        coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 2, estimatedMinutes: 4, pointValue: 50, maxConcurrentTeams: 9,
        steps: [
          { id: 'st1', prompt: 'Say the magic word', answer: 'open' },
          { id: 'st2', prompt: 'Tap to confirm you found the door' },
          { id: 'st3', prompt: 'Year on the plaque?', answer: '1899' },
        ],
      }] },
    ],
  });
  const { runId: r4, accessCode: c4 } = await creator.call('launchRun', { gameId: g4 });
  const player4 = makeParty('player4');
  await signInAnonymously(player4.auth);
  await player4.call('joinRun', { code: c4, displayName: 'Quizzer' });
  await creator.call('startTeams', { gameId: g4, runId: r4 });
  const C4 = { ownerUid: creatorCred.user.uid, gameId: g4, runId: r4 };

  // quiz: secrets stripped, choices present; wrong rejected, right advances
  const sq = await player4.call('getMyTeamState', { code: c4 });
  const qTask = sq?.activeStageTasks?.[0];
  check('quiz: answers stripped but choices sent', qTask?.answers === undefined && Array.isArray(qTask?.choices), JSON.stringify({ answers: qTask?.answers, choices: qTask?.choices }));
  const wrongQ = await player4.call('submitTaskAnswer', { ...C4, taskId: 'q1', answer: 'London' });
  check('quiz: wrong answer rejected', wrongQ?.correct === false);
  const rightQ = await player4.call('submitTaskAnswer', { ...C4, taskId: 'q1', answer: 'paris' });
  check('quiz: correct answer (case-insensitive) advances', rightQ?.correct === true);

  // numeric: within tolerance
  const wrongN = await player4.call('submitTaskAnswer', { ...C4, taskId: 'n1', answer: '20' });
  check('numeric: out-of-tolerance rejected', wrongN?.correct === false);
  const rightN = await player4.call('submitTaskAnswer', { ...C4, taskId: 'n1', answer: '11' });
  check('numeric: within ±tolerance accepted', rightN?.correct === true);

  // geofence: far rejected, near accepted (server validates GPS)
  let geoFar = false;
  try { await player4.call('completeTask', { ...C4, taskId: 'gf1', lat: 32.5, lng: 35.9 }); }
  catch (e) { geoFar = /too far/i.test(e.message); }
  check('geofence: too-far check-in rejected', geoFar);
  const geoNear = await player4.call('completeTask', { ...C4, taskId: 'gf1', lat: 31.78, lng: 35.21 });
  check('geofence: in-radius check-in accepted', geoNear?.ok === true);

  // exact (triggerMode): tight 4m radius — 10m away rejected, 3m accepted.
  let exFar = false;
  try { await player4.call('completeTask', { ...C4, taskId: 'ex1', lat: 31.7801, lng: 35.21 }); }
  catch (e) { exFar = /too far/i.test(e.message); }
  check('exact: 10m-away check-in rejected', exFar);
  const exNear = await player4.call('completeTask', { ...C4, taskId: 'ex1', lat: 31.78, lng: 35.21 });
  check('exact: within-4m check-in accepted', exNear?.ok === true);

  // instant (triggerMode): completes with no GPS at all.
  const inst = await player4.call('completeTask', { ...C4, taskId: 'in1' });
  check('instant: completes with no coordinates', inst?.ok === true);

  // sequence: step prompts sent (no answers); steps advance in order
  const sSeq = await player4.call('getMyTeamState', { code: c4 });
  const seqTask = sSeq?.activeStageTasks?.[0];
  check('sequence: step prompts sent without answers',
    Array.isArray(seqTask?.steps) && seqTask.steps.length === 3 && seqTask.steps.every((s) => s.answer === undefined),
    JSON.stringify(seqTask?.steps));
  const seq0 = await player4.call('submitSequenceStep', { ...C4, taskId: 'sq1', stepIndex: 0, answer: 'open' });
  check('sequence: step 1 (answer) accepted', seq0?.stepCorrect === true && seq0?.stepsDone === 1);
  const seq1 = await player4.call('submitSequenceStep', { ...C4, taskId: 'sq1', stepIndex: 1 });
  check('sequence: step 2 (tap-to-confirm) accepted', seq1?.stepCorrect === true && seq1?.stepsDone === 2);
  const seqBad = await player4.call('submitSequenceStep', { ...C4, taskId: 'sq1', stepIndex: 2, answer: 'nope' });
  check('sequence: wrong final answer rejected', seqBad?.stepCorrect === false);
  const seq2 = await player4.call('submitSequenceStep', { ...C4, taskId: 'sq1', stepIndex: 2, answer: '1899' });
  check('sequence: final step completes the task', seq2?.taskComplete === true);
  const fin4 = await player4.call('getMyTeamState', { code: c4 });
  check('all four task types completed → team finished', fin4?.team?.status === 'finished', fin4?.team?.status);

  // ── 15. Free mode: no consumption + referral (free-run bonus, once) ─────────
  // In free mode all 4 launches were free, so nothing was consumed: the wallet
  // still shows the full 3 lifetime free runs and 0 credits. The referral
  // mechanics below are retained (dark) and still bookkeep the wallet.
  const preRef = await creator.call('getWalletStatus');
  check('free mode: 4 launches consumed no free runs (still 3)', preRef?.freeRunsRemaining === 3, JSON.stringify(preRef));
  check('free mode: no Event Credits spent', preRef?.eventCredits === 0, JSON.stringify(preRef));

  const newbie = makeParty('newbie');
  const newbieCred = await signInAnonymously(newbie.auth);

  let selfRejected = false;
  try { await newbie.call('claimReferral', { referrerUid: newbieCred.user.uid }); }
  catch (e) { selfRejected = /yourself/i.test(e.message); }
  check('claimReferral rejects self-referral', selfRejected);

  const claim = await newbie.call('claimReferral', { referrerUid: creatorCred.user.uid });
  check('claimReferral grants a free run to the newcomer', claim?.ok === true && claim?.bonusFreeRuns > 0, JSON.stringify(claim));
  const newbieStatus = await newbie.call('getWalletStatus');
  check('newcomer free runs bumped', newbieStatus?.freeRunsRemaining === 3 + claim.bonusFreeRuns, JSON.stringify(newbieStatus));
  const newbieWallet = (await newbie.call('getWallet')).wallet;
  check('newcomer referredBy set', newbieWallet.referredBy === creatorCred.user.uid, newbieWallet.referredBy);

  const refAfter = await creator.call('getWalletStatus');
  check('inviter earns an extra free run',
    refAfter?.freeRunsRemaining === preRef.freeRunsRemaining + claim.bonusFreeRuns,
    JSON.stringify({ before: preRef.freeRunsRemaining, after: refAfter.freeRunsRemaining }));
  const refWallet = (await creator.call('getWallet')).wallet;
  check('inviter referralCount bumped', (refWallet.referralCount ?? 0) >= 1, String(refWallet.referralCount));

  const claimAgain = await newbie.call('claimReferral', { referrerUid: creatorCred.user.uid });
  check('claimReferral is one-time per account', claimAgain?.alreadyClaimed === true && claimAgain?.bonusFreeRuns === 0, JSON.stringify(claimAgain));
  const refUnchanged = await creator.call('getWalletStatus');
  check('re-claim does NOT double-grant the inviter', refUnchanged?.freeRunsRemaining === refAfter.freeRunsRemaining, JSON.stringify(refUnchanged));

  // ── 16. Answer attempt limit (anti-cheat row 42) ───────────────────────────
  // A quiz with attemptLimit:2 — two wrong answers exhaust it; the 3rd attempt is
  // refused with resource-exhausted, even though it would be correct.
  const { gameId: g5 } = await creator.call('createGame', { title: 'Attempt-Limit Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g5, scoringPreset: 'fixed_points_speed',
    stages: [{ id: 'al-s', order: 0, title: 'Quiz', isFinal: true, tasks: [{
      id: 'al-q', title: 'Capital of France?', type: 'quiz',
      coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 2, estimatedMinutes: 2, pointValue: 50, maxConcurrentTeams: 9,
      choices: ['Paris', 'London'], answers: ['Paris'],
      smart: { enabled: true, verificationType: 'code_verification', attemptLimit: 2 },
    }] }],
  });
  const { runId: r5, accessCode: c5 } = await creator.call('launchRun', { gameId: g5 });
  const player5 = makeParty('player5');
  await signInAnonymously(player5.auth);
  await player5.call('joinRun', { code: c5, displayName: 'Limiter' });
  await creator.call('startTeams', { gameId: g5, runId: r5 });
  const C5 = { ownerUid: creatorCred.user.uid, gameId: g5, runId: r5 };
  const w1 = await player5.call('submitTaskAnswer', { ...C5, taskId: 'al-q', answer: 'London' });
  check('attempt-limit: 1st wrong answer rejected (not exhausted)', w1?.correct === false);
  const w2 = await player5.call('submitTaskAnswer', { ...C5, taskId: 'al-q', answer: 'London' });
  check('attempt-limit: 2nd wrong answer rejected (limit reached)', w2?.correct === false);
  let attemptExhausted = false;
  try {
    await player5.call('submitTaskAnswer', { ...C5, taskId: 'al-q', answer: 'Paris' }); // would be correct
  } catch (e) {
    attemptExhausted = e.code === 'functions/resource-exhausted' || /attempts left/i.test(e.message);
  }
  check('attempt-limit: 3rd attempt refused even with the correct answer', attemptExhausted);

  // ── 17. Guardian consent gate (guardian-consent-qr) ────────────────────────
  // A consent-required run holds a minor's team in pending-consent: startTeams
  // does NOT launch them until a guardian approves via a single-use token.
  const { gameId: g6 } = await creator.call('createGame', { title: 'Consent Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g6, scoringPreset: 'time_only', requiresGuardianConsent: true, minAge: 13,
    stages: [{ id: 'cs-s', order: 0, title: 'One', isFinal: true, tasks: [{
      id: 'cs-t', title: 'Tap in', type: 'self_report', triggerMode: 'locationless',
      coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 1, estimatedMinutes: 1, pointValue: 10, maxConcurrentTeams: 9,
    }] }],
  });
  const { runId: r6, accessCode: c6 } = await creator.call('launchRun', { gameId: g6 });
  const minor = makeParty('minor');
  await signInAnonymously(minor.auth);
  await minor.call('joinRun', { code: c6, displayName: 'Kid' });
  const start1 = await creator.call('startTeams', { gameId: g6, runId: r6 });
  check('consent: team is NOT started before consent', start1?.launched === 0, JSON.stringify(start1));

  const { token } = await minor.call('requestGuardianConsent', {
    ownerUid: creatorCred.user.uid, gameId: g6, runId: r6, teamId: minor.auth.currentUser.uid,
  });
  check('requestGuardianConsent issues a token', !!token, token);

  // A guardian (separate device) approves with the single-use token.
  const guardian = makeParty('guardian');
  await signInAnonymously(guardian.auth);
  const grant = await guardian.call('grantGuardianConsent', {
    ownerUid: creatorCred.user.uid, gameId: g6, runId: r6, token, guardianName: 'A. Parent',
  });
  check('grantGuardianConsent records consent', grant?.ok === true);

  let tokenReused = false;
  try {
    await guardian.call('grantGuardianConsent', { ownerUid: creatorCred.user.uid, gameId: g6, runId: r6, token, guardianName: 'Again' });
  } catch (e) { tokenReused = e.code === 'functions/failed-precondition' || /already used/i.test(e.message); }
  check('consent: a used token is refused', tokenReused);

  const start2 = await creator.call('startTeams', { gameId: g6, runId: r6 });
  check('consent: team starts after a guardian approves', start2?.launched === 1, JSON.stringify(start2));

  // ── 18. Safe-zone boundary (safe-zone-boundary) ────────────────────────────
  // A location outside the zone flags the team out-of-bounds and soft-pauses new
  // task assignment; returning inside clears the flag and assignment resumes.
  const { gameId: g7 } = await creator.call('createGame', { title: 'Safe Zone Game', mode: 'individual' });
  await creator.call('updateGame', {
    gameId: g7, scoringPreset: 'time_only',
    safeZone: { center: { lat: 31.78, lng: 35.21 }, radiusMeters: 200 },
    stages: [{ id: 'sz-s', order: 0, title: 'Play', isFinal: true, requiredTaskCount: 1, tasks: [
      { id: 'sz-a', title: 'A', type: 'self_report', triggerMode: 'locationless', coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 1, estimatedMinutes: 1, pointValue: 10, maxConcurrentTeams: 9 },
      { id: 'sz-b', title: 'B', type: 'self_report', triggerMode: 'locationless', coordinates: { lat: 0, lng: 0 }, locationless: true, difficulty: 1, estimatedMinutes: 1, pointValue: 10, maxConcurrentTeams: 9 },
    ] }],
  });
  const { runId: r7, accessCode: c7 } = await creator.call('launchRun', { gameId: g7 });
  const wanderer = makeParty('wanderer');
  await signInAnonymously(wanderer.auth);
  await wanderer.call('joinRun', { code: c7, displayName: 'Wanderer' });
  await creator.call('startTeams', { gameId: g7, runId: r7 });
  const C7 = { ownerUid: creatorCred.user.uid, gameId: g7, runId: r7 };

  const breach = await wanderer.call('updateLocation', { ...C7, lat: 32.5, lng: 35.9 });
  check('safe-zone: out-of-zone location flags outOfBounds + alerts', breach?.outOfBounds === true, JSON.stringify(breach));
  const paused = await wanderer.call('requestNextTask', { ...C7, lat: 32.5, lng: 35.9 });
  check('safe-zone: no new task while out of bounds (soft-pause)', paused?.taskId === null && paused?.outOfBounds === true, JSON.stringify(paused));
  const back = await wanderer.call('updateLocation', { ...C7, lat: 31.78, lng: 35.21 });
  check('safe-zone: returning inside clears outOfBounds', back?.outOfBounds === false, JSON.stringify(back));
  const resumed = await wanderer.call('requestNextTask', { ...C7, lat: 31.78, lng: 35.21 });
  check('safe-zone: assignment resumes inside the zone', resumed?.outOfBounds !== true, JSON.stringify(resumed));

  // ── Discovery POIs (surprise-trivia-waypoints) ──────────────────────────────
  {
    const { gameId: dpGame } = await creator.call('createGame', { title: 'Discovery Game', mode: 'individual' });
    const POI = { lat: 31.79, lng: 35.16 };
    await creator.call('updateGame', {
      gameId: dpGame, scoringPreset: 'fixed_points_speed',
      stages: [{ id: 'dp-s', order: 0, title: 'Stage', isFinal: true,
        tasks: [{ id: 'dp-t', title: 'Go', type: 'field', coordinates: { lat: 31.78, lng: 35.21 }, difficulty: 2, estimatedMinutes: 5, pointValue: 50, maxConcurrentTeams: 3 }] }],
    });
    // Creator writes a hidden POI directly (owner rules allow; coords are secret).
    await creator.setDocAt(`users/${creatorCred.user.uid}/games/${dpGame}/discoveryPois/poiA`, {
      id: 'poiA', coordinates: POI, radiusMeters: 200, title: 'Old fountain',
      flavorText: 'You spot something...', question: 'What is this landmark?',
      answers: ['Fountain', 'fountain'], bonusPoints: 40,
    });

    const { runId: dpRun, accessCode: dpCode } = await creator.call('launchRun', { gameId: dpGame });
    const dpPlayer = makeParty('dpPlayer');
    await signInAnonymously(dpPlayer.auth);
    await dpPlayer.call('joinRun', { code: dpCode, displayName: 'Explorer' });
    await creator.call('startTeams', { gameId: dpGame, runId: dpRun });

    // getRunDiscoveryPois never leaks coordinates or answers.
    const list = await dpPlayer.call('getRunDiscoveryPois', { code: dpCode });
    const got = list?.pois?.[0];
    check('discovery: getRunDiscoveryPois returns the POI', got?.id === 'poiA', JSON.stringify(got));
    check('discovery: payload has NO coordinates or answers',
      got && !('coordinates' in got) && !('answers' in got), JSON.stringify(Object.keys(got ?? {})));

    const before = (await dpPlayer.call('getMyTeamState', { code: dpCode }))?.team?.score ?? 0;

    // Outside radius → failed-precondition.
    let outside = false;
    try { await dpPlayer.call('claimDiscoveryPoi', { code: dpCode, poiId: 'poiA', lat: 32.5, lng: 35.9, answer: 'Fountain' }); }
    catch (e) { outside = e.code === 'functions/failed-precondition'; }
    check('discovery: outside radius → failed-precondition', outside);

    // Wrong answer inside radius → no points.
    const wrong = await dpPlayer.call('claimDiscoveryPoi', { code: dpCode, poiId: 'poiA', lat: POI.lat, lng: POI.lng, answer: 'Statue' });
    check('discovery: wrong answer → {correct:false}', wrong?.correct === false, JSON.stringify(wrong));
    const afterWrong = (await dpPlayer.call('getMyTeamState', { code: dpCode }))?.team?.score ?? 0;
    check('discovery: wrong answer awards no points', afterWrong === before, `before=${before} after=${afterWrong}`);

    // Correct answer inside radius → bonus.
    const right = await dpPlayer.call('claimDiscoveryPoi', { code: dpCode, poiId: 'poiA', lat: POI.lat, lng: POI.lng, answer: 'fountain' });
    check('discovery: correct answer → {correct:true} + bonus', right?.correct === true && right?.bonus === 40, JSON.stringify(right));
    const afterRight = (await dpPlayer.call('getMyTeamState', { code: dpCode }))?.team?.score ?? 0;
    check('discovery: correct answer increases score by the bonus', afterRight === before + 40, `before=${before} after=${afterRight}`);

    // Double-claim → already-exists.
    let dup = false;
    try { await dpPlayer.call('claimDiscoveryPoi', { code: dpCode, poiId: 'poiA', lat: POI.lat, lng: POI.lng, answer: 'fountain' }); }
    catch (e) { dup = e.code === 'functions/already-exists'; }
    check('discovery: double-claim → already-exists', dup);
  }

  // ── Hot Zone bonus (activate/deactivate + multiplied score) ─────────────────
  {
    const { gameId: hzGame } = await creator.call('createGame', { title: 'Hot Zone Game', mode: 'individual' });
    const CENTER = { lat: 31.79, lng: 35.16 };
    const FAR = { lat: 31.85, lng: 35.30 }; // ~15km away — outside any zone
    await creator.call('updateGame', {
      gameId: hzGame,
      scoringPreset: 'fixed_points_speed',
      stages: [{
        id: 'hz-stage', order: 0, title: 'Hot Zone stage', isFinal: true, requiredTaskCount: 2,
        tasks: [
          { id: 'hz-in', title: 'In the zone', type: 'field', coordinates: CENTER, difficulty: 3, estimatedMinutes: 5, pointValue: 80, maxConcurrentTeams: 3 },
          { id: 'hz-out', title: 'Out of zone', type: 'field', coordinates: FAR, difficulty: 3, estimatedMinutes: 5, pointValue: 80, maxConcurrentTeams: 3 },
        ],
      }],
    });
    const { runId: hzRun, accessCode: hzCode } = await creator.call('launchRun', { gameId: hzGame });
    const hzPlayer = makeParty('hzPlayer');
    await signInAnonymously(hzPlayer.auth);
    await hzPlayer.call('joinRun', { code: hzCode, displayName: 'Zoner' });
    await creator.call('startTeams', { gameId: hzGame, runId: hzRun });

    // Activation stamps a bounded zone with start/expiry.
    const act = await creator.call('activateHotZone', {
      gameId: hzGame, runId: hzRun, center: CENTER, radiusMeters: 250, multiplier: 2, durationMinutes: 10,
    });
    check('hot-zone: activation returns a stamped zone', !!act?.hotZone?.startedAt && !!act?.hotZone?.expiresAt, JSON.stringify(act?.hotZone));
    check('hot-zone: multiplier stored', act?.hotZone?.multiplier === 2);

    // Only one active zone — re-activating replaces, not stacks.
    const act2 = await creator.call('activateHotZone', {
      gameId: hzGame, runId: hzRun, center: CENTER, radiusMeters: 250, multiplier: 3, durationMinutes: 10,
    });
    check('hot-zone: re-activation replaces (single zone)', act2?.hotZone?.multiplier === 3);
    // Reset back to 2x for the scoring assertions.
    await creator.call('activateHotZone', { gameId: hzGame, runId: hzRun, center: CENTER, radiusMeters: 250, multiplier: 2, durationMinutes: 10 });

    // Complete both tasks (routing assigns one at a time; re-request after each).
    for (let i = 0; i < 2; i++) {
      let st = await hzPlayer.call('getMyTeamState', { code: hzCode });
      let assigned = st?.team?.stages?.[0]?.tasks?.find((t) => t.status === 'assigned');
      if (!assigned) {
        await hzPlayer.call('requestNextTask', { code: hzCode, lat: CENTER.lat, lng: CENTER.lng });
        st = await hzPlayer.call('getMyTeamState', { code: hzCode });
        assigned = st?.team?.stages?.[0]?.tasks?.find((t) => t.status === 'assigned');
      }
      if (!assigned) break;
      const at = assigned.taskId === 'hz-in' ? CENTER : FAR;
      await hzPlayer.call('completeTask', { taskId: assigned.taskId, code: hzCode, lat: at.lat, lng: at.lng });
    }

    const fin = await hzPlayer.call('getMyTeamState', { code: hzCode });
    const recs = fin?.team?.stages?.[0]?.tasks ?? [];
    const inRec = recs.find((t) => t.taskId === 'hz-in');
    const outRec = recs.find((t) => t.taskId === 'hz-out');
    check('hot-zone: in-zone completion is multiplied ×2',
      inRec?.scoreBreakdown?.hotZoneMultiplier === 2 && inRec?.scoreBreakdown?.total === inRec?.scoreBreakdown?.taskScore * 2,
      JSON.stringify(inRec?.scoreBreakdown));
    check('hot-zone: out-of-zone completion is NOT multiplied',
      !outRec?.scoreBreakdown?.hotZoneMultiplier && outRec?.scoreBreakdown?.total === outRec?.scoreBreakdown?.taskScore,
      JSON.stringify(outRec?.scoreBreakdown));

    const deact = await creator.call('deactivateHotZone', { gameId: hzGame, runId: hzRun });
    check('hot-zone: deactivate clears the zone', deact?.ok === true);
  }

  // ── Challenge a friend (checkChallengeAnswer) ───────────────────────────────
  // Isolated published quiz game so the main lifecycle is untouched.
  {
    const { gameId: chGame } = await creator.call('createGame', { title: 'Challenge Quiz' });
    const QUIZ_ID = 'ch-quiz-1';
    await creator.call('updateGame', {
      gameId: chGame,
      stages: [{
        id: 'ch-stage-1', order: 0, title: 'Quiz', isFinal: true,
        tasks: [{
          id: QUIZ_ID, title: 'Capital of France?', type: 'quiz',
          coordinates: { lat: 31.79, lng: 35.16 }, difficulty: 1,
          estimatedMinutes: 1, pointValue: 10, maxConcurrentTeams: 5,
          answers: ['Paris'],
        }],
      }],
    });

    // Unpublished → refused (no publicGames doc to resolve the owner).
    let refused = false;
    try { await creator.call('checkChallengeAnswer', { gameId: chGame, taskId: QUIZ_ID, answer: 'Paris' }); }
    catch { refused = true; }
    check('challenge: unpublished game is refused', refused);

    await creator.call('publishGame', { gameId: chGame, visibility: 'public' });

    const right = await creator.call('checkChallengeAnswer', { gameId: chGame, taskId: QUIZ_ID, answer: 'paris' });
    check('challenge: correct answer → {correct:true}', right?.correct === true, JSON.stringify(right));
    const wrong = await creator.call('checkChallengeAnswer', { gameId: chGame, taskId: QUIZ_ID, answer: 'London' });
    check('challenge: wrong answer → {correct:false}', wrong?.correct === false, JSON.stringify(wrong));
    // The answer key must NEVER appear in the response — only { correct }.
    const keys = Object.keys(right ?? {});
    check('challenge: payload exposes only {correct}', keys.length === 1 && keys[0] === 'correct', JSON.stringify(keys));

    let missing = false;
    try { await creator.call('checkChallengeAnswer', { gameId: chGame, taskId: 'no-such-task', answer: 'x' }); }
    catch (e) { missing = e.code === 'functions/not-found'; }
    check('challenge: unknown task → not-found', missing);
  }

  console.log(`\n${failures === 0 ? '✅ ALL PASS' : `❌ ${failures} FAILURE(S)`}`);
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error('\n💥 Uncaught error:', e.message);
  console.error(e);
  process.exit(1);
});
