// Ephemeral end-to-end verification of the v2 multi-tenant model against the
// running emulator. Exercises the full creator → run → participant → finalize
// path through the public callable API (createGame → updateGame → launchRun →
// getJoinInfo → joinRun → startTeams → getMyTeamState → verifyStationCode /
// completeTask → finalizeRun). Each "party" gets its own anonymous identity,
// mirroring the two-app reality (creator-web + play-web).
//
//   node scripts/e2e-verify-v2.mjs
//
import { initializeApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, signInAnonymously } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';

const PROJECT = 'rushpoint-pwa-7daaa';

function makeParty(name) {
  const app = initializeApp(
    { apiKey: 'emulator-key', projectId: PROJECT, appId: `emu-${name}` },
    name,
  );
  const auth = getAuth(app);
  const functions = getFunctions(app);
  connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
  connectFunctionsEmulator(functions, '127.0.0.1', 5001);
  return {
    auth,
    call: (fn, data) => httpsCallable(functions, fn)(data).then((r) => r.data),
  };
}

let failures = 0;
function check(label, cond, detail) {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? ' :: ' + detail : ''}`);
  if (!cond) failures++;
}

async function main() {
  const creator = makeParty('creator');
  const player = makeParty('player');

  const creatorCred = await signInAnonymously(creator.auth);
  const playerCred = await signInAnonymously(player.auth);
  console.log('Creator uid:', creatorCred.user.uid);
  console.log('Player  uid:', playerCred.user.uid, '\n');

  // ── 1. Creator builds a game ────────────────────────────────────────────────
  const { gameId } = await creator.call('createGame', {
    title: 'E2E Verify Game',
    description: 'Generated by e2e-verify-v2',
    mode: 'team',
  });
  check('createGame returns a gameId', !!gameId, gameId);

  const CODE_TASK_ID = 'task-code-1';
  const PLAIN_TASK_ID = 'task-plain-1';
  const stages = [
    {
      id: 'stage-1',
      order: 0,
      title: 'Stage One — code station',
      tasks: [
        {
          id: CODE_TASK_ID,
          title: 'Find the codeword',
          type: 'station',
          coordinates: { lat: 31.79, lng: 35.16 },
          difficulty: 3,
          estimatedMinutes: 10,
          pointValue: 100,
          maxConcurrentTeams: 3,
          smart: {
            enabled: true,
            verificationType: 'code_verification',
            hasCode: true,
            secretCode: 'ZION',
            codeInputLabel: 'Enter codeword',
          },
        },
      ],
    },
    {
      id: 'stage-2',
      order: 1,
      title: 'Stage Two — plain task',
      isFinal: true,
      tasks: [
        {
          id: PLAIN_TASK_ID,
          title: 'Reach the summit',
          type: 'navigation',
          coordinates: { lat: 31.8, lng: 35.17 },
          difficulty: 2,
          estimatedMinutes: 8,
          pointValue: 80,
          maxConcurrentTeams: 3,
        },
      ],
    },
  ];

  await creator.call('updateGame', {
    gameId,
    stages,
    scoringPreset: 'smart_weighted',
  });
  check('updateGame accepted 2 stages', true);

  // ── 2. Launch a run ─────────────────────────────────────────────────────────
  const { runId, accessCode } = await creator.call('launchRun', { gameId });
  check('launchRun returns runId + accessCode', !!runId && !!accessCode, accessCode);

  // ── 3. Participant pre-join lookup ──────────────────────────────────────────
  const joinInfo = await player.call('getJoinInfo', { code: accessCode });
  check('getJoinInfo resolves the game title', joinInfo?.title === 'E2E Verify Game', joinInfo?.title);
  check('getJoinInfo exposes registrationFields', Array.isArray(joinInfo?.registrationFields));
  check('getJoinInfo does NOT leak game stages', joinInfo?.stages === undefined);

  // ── 4. Join the run ─────────────────────────────────────────────────────────
  const joinRes = await player.call('joinRun', {
    code: accessCode,
    displayName: 'The Test Lions',
    memberNames: ['Ari', 'Dan'],
  });
  check('joinRun succeeds', joinRes?.teamId === playerCred.user.uid, joinRes?.teamId);
  check('joinRun is first-time (not alreadyJoined)', joinRes?.alreadyJoined === false);

  // idempotency
  const joinAgain = await player.call('joinRun', { code: accessCode, displayName: 'The Test Lions' });
  check('joinRun is idempotent', joinAgain?.alreadyJoined === true);

  // ── 5. Creator starts the teams ─────────────────────────────────────────────
  const startRes = await creator.call('startTeams', { gameId, runId });
  check('startTeams launched 1 team', startRes?.launched === 1, JSON.stringify(startRes));

  // ── 6. Participant reads their live state ───────────────────────────────────
  let state = await player.call('getMyTeamState', { code: accessCode });
  check('getMyTeamState returns the team', state?.team?.displayName === 'The Test Lions');
  check('team is active after startTeams', state?.team?.status === 'active', state?.team?.status);
  check('first stage is active', state?.team?.stages?.[0]?.status === 'active');
  const activeTask = state?.activeStageTasks?.[0];
  check('active task content is exposed', activeTask?.id === CODE_TASK_ID);
  check('secretCode is stripped from participant payload', activeTask?.smart?.secretCode === undefined);

  // ── 7. Wrong code is rejected, correct code advances ────────────────────────
  let wrongRejected = false;
  try {
    await player.call('verifyStationCode', {
      ownerUid: creatorCred.user.uid, gameId, runId,
      teamId: playerCred.user.uid, taskId: CODE_TASK_ID, code: 'NOPE',
    });
  } catch (e) {
    wrongRejected = /incorrect code/i.test(e.message);
  }
  check('verifyStationCode rejects a wrong code', wrongRejected);

  const verifyRes = await player.call('verifyStationCode', {
    ownerUid: creatorCred.user.uid, gameId, runId,
    teamId: playerCred.user.uid, taskId: CODE_TASK_ID, code: 'zion', // case-insensitive
  });
  check('verifyStationCode accepts the correct code', verifyRes?.verified === true);

  // ── 8. Stage 1 done → stage 2 should unlock ─────────────────────────────────
  state = await player.call('getMyTeamState', { code: accessCode });
  check('stage 1 completed', state?.team?.stages?.[0]?.status === 'completed', state?.team?.stages?.[0]?.status);
  check('stage 2 unlocked (active)', state?.team?.stages?.[1]?.status === 'active', state?.team?.stages?.[1]?.status);
  check('code task scored > 0', (state?.team?.stages?.[0]?.tasks?.[0]?.earnedScore ?? 0) > 0,
    String(state?.team?.stages?.[0]?.tasks?.[0]?.earnedScore));

  // ── 9. Complete the final plain task ────────────────────────────────────────
  const completeRes = await player.call('completeTask', {
    taskId: PLAIN_TASK_ID, code: accessCode, lat: 31.8, lng: 35.17,
  });
  check('completeTask on final task succeeds', completeRes?.ok === true);

  state = await player.call('getMyTeamState', { code: accessCode });
  check('all stages completed', state?.team?.stages?.every((s) => s.status === 'completed'),
    state?.team?.stages?.map((s) => s.status).join(','));
  check('team marked finished', !!state?.team?.finishedAt || state?.team?.status === 'finished',
    state?.team?.status);

  // ── 10. Finalize the run ────────────────────────────────────────────────────
  const fin = await creator.call('finalizeRun', { gameId, runId });
  check('finalizeRun returns rankings', Array.isArray(fin?.rankings) && fin.rankings.length === 1);
  check('our team is ranked #1', fin?.rankings?.[0]?.teamId === playerCred.user.uid, JSON.stringify(fin?.rankings?.[0]));
  check('final score is positive', (fin?.rankings?.[0]?.score ?? 0) > 0, String(fin?.rankings?.[0]?.score));

  console.log(`\n${failures === 0 ? '✅ ALL PASS' : `❌ ${failures} FAILURE(S)`}`);
  process.exit(failures === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error('\n💥 Uncaught error:', e.message);
  console.error(e);
  process.exit(1);
});
